export const TENANT = {
  browserSocketPath: '/ws/tenant',
  daemonSocketPath: '/ws/daemon',
  filePath: '/api/files/',
  daemonKeyHeader: 'x-api-key',
  browserTag: 'browser',
  daemonTag: 'daemon',
  reconnectDelayMs: 2000,
  daemonReplacedCloseCode: 4001,
  revokedCloseCode: 4003,
  daemonProtocol: 2,
  daemonProtocolCloseCode: 4004,
  unresponsiveCloseCode: 1011,
  shutdownCloseCode: 1000,
  ownerHeader: 'x-orbs-socket-owner',
  organizationIdPattern: /^[a-z0-9-]{1,64}$/,
  alarmMaxDelayMs: 2_147_483_647,
  alarmRepassMs: 500,
  alarmBackoffMs: 1000,
  alarmBackoffMaxMs: 60_000,
} as const;
