export const PI = {
  command: 'pi',
  minimumVersion: '0.99.0',
  agentDirEnv: 'PI_CODING_AGENT_DIR',
  userAgentDir: ['.pi', 'agent'],
  tempDirPrefix: 'orbs-pi',
  bridgeFile: 'bridge.ts',
  bridgeFlag: '--orbs',
  daemonAgentDir: 'daemon',
  settingsFile: 'settings.json',
  botPromptFiles: ['SYSTEM.md', 'APPEND_SYSTEM.md'],
  isolatedAgentEntries: ['settings.json', 'mcp.json', 'SYSTEM.md', 'APPEND_SYSTEM.md'],
  builtinExtensionPrefix: 'builtin:',
  excludedBuiltinExtensions: ['-builtin:llama.cpp'],
  baseArgs: ['--mode', 'rpc', '--no-context-files', '--no-skills', '--no-prompt-templates', '--no-themes', '--no-approve'],
  builtinExtensions: ['builtin:mcp', 'builtin:codemode', 'builtin:tool-search'],
  credentialMinExpiry: '30m',
  commands: { memory: 'orbs-memory', catalogue: 'orbs-catalogue' },
  dialogMethods: ['select', 'confirm', 'input', 'editor'],
  sessionsDir: 'sessions',
  agentsFile: 'AGENTS.md',
  mcpFile: 'mcp.json',
  orbsSection: 'orbs',
  instructionsSection: 'instructions',
  roomSection: 'room',
  judgeDir: 'judge',
  judgeTool: 'route',
  hiddenProviders: ['openai'],
  readTools: ['read', 'grep', 'find', 'ls'],
  ungatedTools: ['tool_search', 'codemode'],
  repeatedCallLimit: 3,
  sessionIdleMs: 10 * 60 * 1000,
  extractTimeoutMs: 80_000,
  catalogueTimeoutMs: 30_000,
  stderrTailChars: 2000,
} as const;
