import { compile } from "@inlang/paraglide-js";
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { i18nParaglideOptions } from "../src/entry.vite.ts";

const root = dirname(fileURLToPath(import.meta.url));
const paraglide = resolve(root, "../src/paraglide");

await compile({
  project: resolve(root, "../project.inlang"),
  outdir: paraglide,
  ...i18nParaglideOptions,
});

// Shadow messages/_index.js with a .d.ts of signatures: consumers' tsc reads ~3k
// declarations instead of inferring 4MB of generated JS (OOMs, scales per-locale).
const source = readFileSync(resolve(paraglide, "messages/_index.js"), "utf8");
const inputs = new Map([...source.matchAll(/@typedef \{(.+)\} (\w+) \*\//g)].map(([, type, name]) => [name, type]));

const locales = readdirSync(resolve(root, "../messages"), { withFileTypes: true })
  .filter((e) => e.isDirectory())
  .map((e) => e.name)
  .sort();

const decls = [];
const unparsed = [];

for (const line of source.split("\n")) {
  if (!line.startsWith("export const ")) {
    continue;
  }

  const match = /^export const (\w+) = \/\*\* @type \{\(\(inputs(\??): (\w+),/.exec(line);

  if (!match || !inputs.has(match[3])) {
    unparsed.push(line.slice(0, 80));
    continue;
  }

  const [, key, optional, type] = match;
  decls.push(`export const ${key}: (inputs${optional}: ${inputs.get(type)}, options?: { locale?: Locale }) => string`);
}

if (unparsed.length > 0) {
  throw new Error(`compile.js: ${unparsed.length} message exports did not match the expected shape:\n${unparsed.join("\n")}`);
}

const header = `// AUTO-GENERATED by scripts/compile.js — do not edit\ntype Locale = ${locales.map((l) => `'${l}'`).join(" | ")}\n`;
writeFileSync(resolve(paraglide, "messages/_index.d.ts"), `${header}${decls.join("\n")}\n`);
