/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./../routes/root";
import { Route as indexRouteImport } from "./../routes/index";
import { Route as chatDotlayoutRouteImport } from "./../routes/chat.layout";
import { Route as authAuthDotlayoutRouteImport } from "./../routes/auth/auth.layout";
import { Route as handlersHandlerDotrobotsRouteImport } from "./../routes/handlers/handler.robots";
import { Route as handlersHandlerDotsitemapRouteImport } from "./../routes/handlers/handler.sitemap";
import { Route as authAuthDotforgotPasswordRouteImport } from "./../routes/auth/auth.forgot-password";
import { Route as authAuthDotresetPasswordRouteImport } from "./../routes/auth/auth.reset-password";
import { Route as authAuthDotsignInRouteImport } from "./../routes/auth/auth.sign-in";
import { Route as authAuthDotsignUpRouteImport } from "./../routes/auth/auth.sign-up";
import { Route as authAuthDotverifyEmailRouteImport } from "./../routes/auth/auth.verify-email";
import { Route as labLabDotavatarsRouteImport } from "./../routes/lab/lab.avatars";
import { Route as authAuthDotsignOutRouteImport } from "./../routes/auth/auth.sign-out";
import { Route as handlersHandlerDotrpcRouteImport } from "./../routes/handlers/handler.rpc";
import { Route as handlersHandlerDotingestRouteImport } from "./../routes/handlers/handler.ingest";
import { Route as botsBotsDotcreateRouteImport } from "./../routes/bots/bots.create";
import { Route as roomsRoomsDotindexRouteImport } from "./../routes/rooms/rooms.index";
import { Route as roomsRoomsDotroomIdRouteImport } from "./../routes/rooms/rooms.$roomId";
import { Route as roomsRoomsDotcreateRouteImport } from "./../routes/rooms/rooms.create";
import { Route as settingsSettingsDotdaemonKeyRouteImport } from "./../routes/settings/settings.daemon-key";
import { Route as settingsSettingsDotorganizationRouteImport } from "./../routes/settings/settings.organization";
import { Route as handlersHandlerDotauthRouteImport } from "./../routes/handlers/handler.auth";
import { Route as botsBotsDotbotIdDotdeleteRouteImport } from "./../routes/bots/bots.$botId.delete";
import { Route as botsBotsDotbotIdDoteditRouteImport } from "./../routes/bots/bots.$botId.edit";
import { Route as botsBotsDotbotIdDotwipeMemoryRouteImport } from "./../routes/bots/bots.$botId.wipe-memory";
import { Route as roomsRoomsDotroomIdDotdeleteRouteImport } from "./../routes/rooms/rooms.$roomId.delete";
import { Route as roomsRoomsDotroomIdDotresetRouteImport } from "./../routes/rooms/rooms.$roomId.reset";
import { Route as roomsRoomsDotroomIdDotsettingsRouteImport } from "./../routes/rooms/rooms.$roomId.settings";
import { Route as roomsRoomsDotroomIdDotwipeMemoryRouteImport } from "./../routes/rooms/rooms.$roomId.wipe-memory";
import { Route as roomsRoomsDotdirectDothandleRouteImport } from "./../routes/rooms/rooms.direct.$handle";
import { Route as roomsRoomsDotdirectDothandleDoteditRouteImport } from "./../routes/rooms/rooms.direct.$handle.edit";
import { Route as roomsRoomsDotdirectDothandleDotresetRouteImport } from "./../routes/rooms/rooms.direct.$handle.reset";
import { Route as roomsRoomsDotdirectDothandleDotwipeMemoryRouteImport } from "./../routes/rooms/rooms.direct.$handle.wipe-memory";

const indexRoute = indexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const chatDotlayoutRoute = chatDotlayoutRouteImport.update({
  id: "/_chat",
  getParentRoute: () => rootRouteImport,
} as any);
const authAuthDotlayoutRoute = authAuthDotlayoutRouteImport.update({
  id: "/auth",
  path: "/auth",
  getParentRoute: () => rootRouteImport,
} as any);
const handlersHandlerDotrobotsRoute =
  handlersHandlerDotrobotsRouteImport.update({
    id: "/robots.txt",
    path: "/robots.txt",
    getParentRoute: () => rootRouteImport,
  } as any);
const handlersHandlerDotsitemapRoute =
  handlersHandlerDotsitemapRouteImport.update({
    id: "/sitemap.xml",
    path: "/sitemap.xml",
    getParentRoute: () => rootRouteImport,
  } as any);
const authAuthDotforgotPasswordRoute =
  authAuthDotforgotPasswordRouteImport.update({
    id: "/forgot-password",
    path: "/forgot-password",
    getParentRoute: () => authAuthDotlayoutRoute,
  } as any);
const authAuthDotresetPasswordRoute =
  authAuthDotresetPasswordRouteImport.update({
    id: "/reset-password",
    path: "/reset-password",
    getParentRoute: () => authAuthDotlayoutRoute,
  } as any);
const authAuthDotsignInRoute = authAuthDotsignInRouteImport.update({
  id: "/sign-in",
  path: "/sign-in",
  getParentRoute: () => authAuthDotlayoutRoute,
} as any);
const authAuthDotsignUpRoute = authAuthDotsignUpRouteImport.update({
  id: "/sign-up",
  path: "/sign-up",
  getParentRoute: () => authAuthDotlayoutRoute,
} as any);
const authAuthDotverifyEmailRoute = authAuthDotverifyEmailRouteImport.update({
  id: "/verify-email",
  path: "/verify-email",
  getParentRoute: () => authAuthDotlayoutRoute,
} as any);
const labLabDotavatarsRoute = labLabDotavatarsRouteImport.update({
  id: "/lab/avatars",
  path: "/lab/avatars",
  getParentRoute: () => rootRouteImport,
} as any);
const authAuthDotsignOutRoute = authAuthDotsignOutRouteImport.update({
  id: "/rooms/sign-out",
  path: "/rooms/sign-out",
  getParentRoute: () => rootRouteImport,
} as any);
const handlersHandlerDotrpcRoute = handlersHandlerDotrpcRouteImport.update({
  id: "/rpc/$",
  path: "/rpc/$",
  getParentRoute: () => rootRouteImport,
} as any);
const handlersHandlerDotingestRoute =
  handlersHandlerDotingestRouteImport.update({
    id: "/t/ingest",
    path: "/t/ingest",
    getParentRoute: () => rootRouteImport,
  } as any);
const botsBotsDotcreateRoute = botsBotsDotcreateRouteImport.update({
  id: "/bots/create",
  path: "/bots/create",
  getParentRoute: () => chatDotlayoutRoute,
} as any);
const roomsRoomsDotindexRoute = roomsRoomsDotindexRouteImport.update({
  id: "/rooms/",
  path: "/rooms/",
  getParentRoute: () => chatDotlayoutRoute,
} as any);
const roomsRoomsDotroomIdRoute = roomsRoomsDotroomIdRouteImport.update({
  id: "/rooms/$roomId",
  path: "/rooms/$roomId",
  getParentRoute: () => chatDotlayoutRoute,
} as any);
const roomsRoomsDotcreateRoute = roomsRoomsDotcreateRouteImport.update({
  id: "/rooms/create",
  path: "/rooms/create",
  getParentRoute: () => chatDotlayoutRoute,
} as any);
const settingsSettingsDotdaemonKeyRoute =
  settingsSettingsDotdaemonKeyRouteImport.update({
    id: "/settings/daemon-key",
    path: "/settings/daemon-key",
    getParentRoute: () => chatDotlayoutRoute,
  } as any);
const settingsSettingsDotorganizationRoute =
  settingsSettingsDotorganizationRouteImport.update({
    id: "/settings/organization",
    path: "/settings/organization",
    getParentRoute: () => chatDotlayoutRoute,
  } as any);
const handlersHandlerDotauthRoute = handlersHandlerDotauthRouteImport.update({
  id: "/api/auth/$",
  path: "/api/auth/$",
  getParentRoute: () => rootRouteImport,
} as any);
const botsBotsDotbotIdDotdeleteRoute =
  botsBotsDotbotIdDotdeleteRouteImport.update({
    id: "/bots/$botId/delete",
    path: "/bots/$botId/delete",
    getParentRoute: () => chatDotlayoutRoute,
  } as any);
const botsBotsDotbotIdDoteditRoute = botsBotsDotbotIdDoteditRouteImport.update({
  id: "/bots/$botId/edit",
  path: "/bots/$botId/edit",
  getParentRoute: () => chatDotlayoutRoute,
} as any);
const botsBotsDotbotIdDotwipeMemoryRoute =
  botsBotsDotbotIdDotwipeMemoryRouteImport.update({
    id: "/bots/$botId/wipe-memory",
    path: "/bots/$botId/wipe-memory",
    getParentRoute: () => chatDotlayoutRoute,
  } as any);
const roomsRoomsDotroomIdDotdeleteRoute =
  roomsRoomsDotroomIdDotdeleteRouteImport.update({
    id: "/delete",
    path: "/delete",
    getParentRoute: () => roomsRoomsDotroomIdRoute,
  } as any);
const roomsRoomsDotroomIdDotresetRoute =
  roomsRoomsDotroomIdDotresetRouteImport.update({
    id: "/reset",
    path: "/reset",
    getParentRoute: () => roomsRoomsDotroomIdRoute,
  } as any);
const roomsRoomsDotroomIdDotsettingsRoute =
  roomsRoomsDotroomIdDotsettingsRouteImport.update({
    id: "/settings",
    path: "/settings",
    getParentRoute: () => roomsRoomsDotroomIdRoute,
  } as any);
const roomsRoomsDotroomIdDotwipeMemoryRoute =
  roomsRoomsDotroomIdDotwipeMemoryRouteImport.update({
    id: "/wipe-memory",
    path: "/wipe-memory",
    getParentRoute: () => roomsRoomsDotroomIdRoute,
  } as any);
const roomsRoomsDotdirectDothandleRoute =
  roomsRoomsDotdirectDothandleRouteImport.update({
    id: "/rooms/direct/$handle",
    path: "/rooms/direct/$handle",
    getParentRoute: () => chatDotlayoutRoute,
  } as any);
const roomsRoomsDotdirectDothandleDoteditRoute =
  roomsRoomsDotdirectDothandleDoteditRouteImport.update({
    id: "/edit",
    path: "/edit",
    getParentRoute: () => roomsRoomsDotdirectDothandleRoute,
  } as any);
const roomsRoomsDotdirectDothandleDotresetRoute =
  roomsRoomsDotdirectDothandleDotresetRouteImport.update({
    id: "/reset",
    path: "/reset",
    getParentRoute: () => roomsRoomsDotdirectDothandleRoute,
  } as any);
const roomsRoomsDotdirectDothandleDotwipeMemoryRoute =
  roomsRoomsDotdirectDothandleDotwipeMemoryRouteImport.update({
    id: "/wipe-memory",
    path: "/wipe-memory",
    getParentRoute: () => roomsRoomsDotdirectDothandleRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof indexRoute;
  "/auth": typeof authAuthDotlayoutRouteWithChildren;
  "/robots.txt": typeof handlersHandlerDotrobotsRoute;
  "/sitemap.xml": typeof handlersHandlerDotsitemapRoute;
  "/auth/forgot-password": typeof authAuthDotforgotPasswordRoute;
  "/auth/reset-password": typeof authAuthDotresetPasswordRoute;
  "/auth/sign-in": typeof authAuthDotsignInRoute;
  "/auth/sign-up": typeof authAuthDotsignUpRoute;
  "/auth/verify-email": typeof authAuthDotverifyEmailRoute;
  "/lab/avatars": typeof labLabDotavatarsRoute;
  "/rooms/sign-out": typeof authAuthDotsignOutRoute;
  "/rpc/$": typeof handlersHandlerDotrpcRoute;
  "/t/ingest": typeof handlersHandlerDotingestRoute;
  "/bots/create": typeof botsBotsDotcreateRoute;
  "/rooms/$roomId": typeof roomsRoomsDotroomIdRouteWithChildren;
  "/rooms/create": typeof roomsRoomsDotcreateRoute;
  "/settings/daemon-key": typeof settingsSettingsDotdaemonKeyRoute;
  "/settings/organization": typeof settingsSettingsDotorganizationRoute;
  "/api/auth/$": typeof handlersHandlerDotauthRoute;
  "/rooms/": typeof roomsRoomsDotindexRoute;
  "/bots/$botId/delete": typeof botsBotsDotbotIdDotdeleteRoute;
  "/bots/$botId/edit": typeof botsBotsDotbotIdDoteditRoute;
  "/bots/$botId/wipe-memory": typeof botsBotsDotbotIdDotwipeMemoryRoute;
  "/rooms/$roomId/delete": typeof roomsRoomsDotroomIdDotdeleteRoute;
  "/rooms/$roomId/reset": typeof roomsRoomsDotroomIdDotresetRoute;
  "/rooms/$roomId/settings": typeof roomsRoomsDotroomIdDotsettingsRoute;
  "/rooms/$roomId/wipe-memory": typeof roomsRoomsDotroomIdDotwipeMemoryRoute;
  "/rooms/direct/$handle": typeof roomsRoomsDotdirectDothandleRouteWithChildren;
  "/rooms/direct/$handle/edit": typeof roomsRoomsDotdirectDothandleDoteditRoute;
  "/rooms/direct/$handle/reset": typeof roomsRoomsDotdirectDothandleDotresetRoute;
  "/rooms/direct/$handle/wipe-memory": typeof roomsRoomsDotdirectDothandleDotwipeMemoryRoute;
}
export interface FileRoutesByTo {
  "/": typeof indexRoute;
  "/auth": typeof authAuthDotlayoutRouteWithChildren;
  "/robots.txt": typeof handlersHandlerDotrobotsRoute;
  "/sitemap.xml": typeof handlersHandlerDotsitemapRoute;
  "/auth/forgot-password": typeof authAuthDotforgotPasswordRoute;
  "/auth/reset-password": typeof authAuthDotresetPasswordRoute;
  "/auth/sign-in": typeof authAuthDotsignInRoute;
  "/auth/sign-up": typeof authAuthDotsignUpRoute;
  "/auth/verify-email": typeof authAuthDotverifyEmailRoute;
  "/lab/avatars": typeof labLabDotavatarsRoute;
  "/rooms/sign-out": typeof authAuthDotsignOutRoute;
  "/rpc/$": typeof handlersHandlerDotrpcRoute;
  "/t/ingest": typeof handlersHandlerDotingestRoute;
  "/bots/create": typeof botsBotsDotcreateRoute;
  "/rooms/$roomId": typeof roomsRoomsDotroomIdRouteWithChildren;
  "/rooms/create": typeof roomsRoomsDotcreateRoute;
  "/settings/daemon-key": typeof settingsSettingsDotdaemonKeyRoute;
  "/settings/organization": typeof settingsSettingsDotorganizationRoute;
  "/api/auth/$": typeof handlersHandlerDotauthRoute;
  "/rooms": typeof roomsRoomsDotindexRoute;
  "/bots/$botId/delete": typeof botsBotsDotbotIdDotdeleteRoute;
  "/bots/$botId/edit": typeof botsBotsDotbotIdDoteditRoute;
  "/bots/$botId/wipe-memory": typeof botsBotsDotbotIdDotwipeMemoryRoute;
  "/rooms/$roomId/delete": typeof roomsRoomsDotroomIdDotdeleteRoute;
  "/rooms/$roomId/reset": typeof roomsRoomsDotroomIdDotresetRoute;
  "/rooms/$roomId/settings": typeof roomsRoomsDotroomIdDotsettingsRoute;
  "/rooms/$roomId/wipe-memory": typeof roomsRoomsDotroomIdDotwipeMemoryRoute;
  "/rooms/direct/$handle": typeof roomsRoomsDotdirectDothandleRouteWithChildren;
  "/rooms/direct/$handle/edit": typeof roomsRoomsDotdirectDothandleDoteditRoute;
  "/rooms/direct/$handle/reset": typeof roomsRoomsDotdirectDothandleDotresetRoute;
  "/rooms/direct/$handle/wipe-memory": typeof roomsRoomsDotdirectDothandleDotwipeMemoryRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof indexRoute;
  "/_chat": typeof chatDotlayoutRouteWithChildren;
  "/auth": typeof authAuthDotlayoutRouteWithChildren;
  "/robots.txt": typeof handlersHandlerDotrobotsRoute;
  "/sitemap.xml": typeof handlersHandlerDotsitemapRoute;
  "/auth/forgot-password": typeof authAuthDotforgotPasswordRoute;
  "/auth/reset-password": typeof authAuthDotresetPasswordRoute;
  "/auth/sign-in": typeof authAuthDotsignInRoute;
  "/auth/sign-up": typeof authAuthDotsignUpRoute;
  "/auth/verify-email": typeof authAuthDotverifyEmailRoute;
  "/lab/avatars": typeof labLabDotavatarsRoute;
  "/rooms/sign-out": typeof authAuthDotsignOutRoute;
  "/rpc/$": typeof handlersHandlerDotrpcRoute;
  "/t/ingest": typeof handlersHandlerDotingestRoute;
  "/_chat/bots/create": typeof botsBotsDotcreateRoute;
  "/_chat/rooms/$roomId": typeof roomsRoomsDotroomIdRouteWithChildren;
  "/_chat/rooms/create": typeof roomsRoomsDotcreateRoute;
  "/_chat/settings/daemon-key": typeof settingsSettingsDotdaemonKeyRoute;
  "/_chat/settings/organization": typeof settingsSettingsDotorganizationRoute;
  "/api/auth/$": typeof handlersHandlerDotauthRoute;
  "/_chat/rooms/": typeof roomsRoomsDotindexRoute;
  "/_chat/bots/$botId/delete": typeof botsBotsDotbotIdDotdeleteRoute;
  "/_chat/bots/$botId/edit": typeof botsBotsDotbotIdDoteditRoute;
  "/_chat/bots/$botId/wipe-memory": typeof botsBotsDotbotIdDotwipeMemoryRoute;
  "/_chat/rooms/$roomId/delete": typeof roomsRoomsDotroomIdDotdeleteRoute;
  "/_chat/rooms/$roomId/reset": typeof roomsRoomsDotroomIdDotresetRoute;
  "/_chat/rooms/$roomId/settings": typeof roomsRoomsDotroomIdDotsettingsRoute;
  "/_chat/rooms/$roomId/wipe-memory": typeof roomsRoomsDotroomIdDotwipeMemoryRoute;
  "/_chat/rooms/direct/$handle": typeof roomsRoomsDotdirectDothandleRouteWithChildren;
  "/_chat/rooms/direct/$handle/edit": typeof roomsRoomsDotdirectDothandleDoteditRoute;
  "/_chat/rooms/direct/$handle/reset": typeof roomsRoomsDotdirectDothandleDotresetRoute;
  "/_chat/rooms/direct/$handle/wipe-memory": typeof roomsRoomsDotdirectDothandleDotwipeMemoryRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/auth"
    | "/robots.txt"
    | "/sitemap.xml"
    | "/auth/forgot-password"
    | "/auth/reset-password"
    | "/auth/sign-in"
    | "/auth/sign-up"
    | "/auth/verify-email"
    | "/lab/avatars"
    | "/rooms/sign-out"
    | "/rpc/$"
    | "/t/ingest"
    | "/bots/create"
    | "/rooms/$roomId"
    | "/rooms/create"
    | "/settings/daemon-key"
    | "/settings/organization"
    | "/api/auth/$"
    | "/rooms/"
    | "/bots/$botId/delete"
    | "/bots/$botId/edit"
    | "/bots/$botId/wipe-memory"
    | "/rooms/$roomId/delete"
    | "/rooms/$roomId/reset"
    | "/rooms/$roomId/settings"
    | "/rooms/$roomId/wipe-memory"
    | "/rooms/direct/$handle"
    | "/rooms/direct/$handle/edit"
    | "/rooms/direct/$handle/reset"
    | "/rooms/direct/$handle/wipe-memory";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/auth"
    | "/robots.txt"
    | "/sitemap.xml"
    | "/auth/forgot-password"
    | "/auth/reset-password"
    | "/auth/sign-in"
    | "/auth/sign-up"
    | "/auth/verify-email"
    | "/lab/avatars"
    | "/rooms/sign-out"
    | "/rpc/$"
    | "/t/ingest"
    | "/bots/create"
    | "/rooms/$roomId"
    | "/rooms/create"
    | "/settings/daemon-key"
    | "/settings/organization"
    | "/api/auth/$"
    | "/rooms"
    | "/bots/$botId/delete"
    | "/bots/$botId/edit"
    | "/bots/$botId/wipe-memory"
    | "/rooms/$roomId/delete"
    | "/rooms/$roomId/reset"
    | "/rooms/$roomId/settings"
    | "/rooms/$roomId/wipe-memory"
    | "/rooms/direct/$handle"
    | "/rooms/direct/$handle/edit"
    | "/rooms/direct/$handle/reset"
    | "/rooms/direct/$handle/wipe-memory";
  id:
    | "__root__"
    | "/"
    | "/_chat"
    | "/auth"
    | "/robots.txt"
    | "/sitemap.xml"
    | "/auth/forgot-password"
    | "/auth/reset-password"
    | "/auth/sign-in"
    | "/auth/sign-up"
    | "/auth/verify-email"
    | "/lab/avatars"
    | "/rooms/sign-out"
    | "/rpc/$"
    | "/t/ingest"
    | "/_chat/bots/create"
    | "/_chat/rooms/$roomId"
    | "/_chat/rooms/create"
    | "/_chat/settings/daemon-key"
    | "/_chat/settings/organization"
    | "/api/auth/$"
    | "/_chat/rooms/"
    | "/_chat/bots/$botId/delete"
    | "/_chat/bots/$botId/edit"
    | "/_chat/bots/$botId/wipe-memory"
    | "/_chat/rooms/$roomId/delete"
    | "/_chat/rooms/$roomId/reset"
    | "/_chat/rooms/$roomId/settings"
    | "/_chat/rooms/$roomId/wipe-memory"
    | "/_chat/rooms/direct/$handle"
    | "/_chat/rooms/direct/$handle/edit"
    | "/_chat/rooms/direct/$handle/reset"
    | "/_chat/rooms/direct/$handle/wipe-memory";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  indexRoute: typeof indexRoute;
  chatDotlayoutRoute: typeof chatDotlayoutRouteWithChildren;
  authAuthDotlayoutRoute: typeof authAuthDotlayoutRouteWithChildren;
  handlersHandlerDotrobotsRoute: typeof handlersHandlerDotrobotsRoute;
  handlersHandlerDotsitemapRoute: typeof handlersHandlerDotsitemapRoute;
  labLabDotavatarsRoute: typeof labLabDotavatarsRoute;
  authAuthDotsignOutRoute: typeof authAuthDotsignOutRoute;
  handlersHandlerDotrpcRoute: typeof handlersHandlerDotrpcRoute;
  handlersHandlerDotingestRoute: typeof handlersHandlerDotingestRoute;
  handlersHandlerDotauthRoute: typeof handlersHandlerDotauthRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof indexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_chat": {
      id: "/_chat";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof chatDotlayoutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth": {
      id: "/auth";
      path: "/auth";
      fullPath: "/auth";
      preLoaderRoute: typeof authAuthDotlayoutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/robots.txt": {
      id: "/robots.txt";
      path: "/robots.txt";
      fullPath: "/robots.txt";
      preLoaderRoute: typeof handlersHandlerDotrobotsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/sitemap.xml": {
      id: "/sitemap.xml";
      path: "/sitemap.xml";
      fullPath: "/sitemap.xml";
      preLoaderRoute: typeof handlersHandlerDotsitemapRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth/forgot-password": {
      id: "/auth/forgot-password";
      path: "/forgot-password";
      fullPath: "/auth/forgot-password";
      preLoaderRoute: typeof authAuthDotforgotPasswordRouteImport;
      parentRoute: typeof authAuthDotlayoutRoute;
    };
    "/auth/reset-password": {
      id: "/auth/reset-password";
      path: "/reset-password";
      fullPath: "/auth/reset-password";
      preLoaderRoute: typeof authAuthDotresetPasswordRouteImport;
      parentRoute: typeof authAuthDotlayoutRoute;
    };
    "/auth/sign-in": {
      id: "/auth/sign-in";
      path: "/sign-in";
      fullPath: "/auth/sign-in";
      preLoaderRoute: typeof authAuthDotsignInRouteImport;
      parentRoute: typeof authAuthDotlayoutRoute;
    };
    "/auth/sign-up": {
      id: "/auth/sign-up";
      path: "/sign-up";
      fullPath: "/auth/sign-up";
      preLoaderRoute: typeof authAuthDotsignUpRouteImport;
      parentRoute: typeof authAuthDotlayoutRoute;
    };
    "/auth/verify-email": {
      id: "/auth/verify-email";
      path: "/verify-email";
      fullPath: "/auth/verify-email";
      preLoaderRoute: typeof authAuthDotverifyEmailRouteImport;
      parentRoute: typeof authAuthDotlayoutRoute;
    };
    "/lab/avatars": {
      id: "/lab/avatars";
      path: "/lab/avatars";
      fullPath: "/lab/avatars";
      preLoaderRoute: typeof labLabDotavatarsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/rooms/sign-out": {
      id: "/rooms/sign-out";
      path: "/rooms/sign-out";
      fullPath: "/rooms/sign-out";
      preLoaderRoute: typeof authAuthDotsignOutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/rpc/$": {
      id: "/rpc/$";
      path: "/rpc/$";
      fullPath: "/rpc/$";
      preLoaderRoute: typeof handlersHandlerDotrpcRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/t/ingest": {
      id: "/t/ingest";
      path: "/t/ingest";
      fullPath: "/t/ingest";
      preLoaderRoute: typeof handlersHandlerDotingestRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_chat/bots/create": {
      id: "/_chat/bots/create";
      path: "/bots/create";
      fullPath: "/bots/create";
      preLoaderRoute: typeof botsBotsDotcreateRouteImport;
      parentRoute: typeof chatDotlayoutRoute;
    };
    "/_chat/rooms/": {
      id: "/_chat/rooms/";
      path: "/rooms";
      fullPath: "/rooms/";
      preLoaderRoute: typeof roomsRoomsDotindexRouteImport;
      parentRoute: typeof chatDotlayoutRoute;
    };
    "/_chat/rooms/$roomId": {
      id: "/_chat/rooms/$roomId";
      path: "/rooms/$roomId";
      fullPath: "/rooms/$roomId";
      preLoaderRoute: typeof roomsRoomsDotroomIdRouteImport;
      parentRoute: typeof chatDotlayoutRoute;
    };
    "/_chat/rooms/create": {
      id: "/_chat/rooms/create";
      path: "/rooms/create";
      fullPath: "/rooms/create";
      preLoaderRoute: typeof roomsRoomsDotcreateRouteImport;
      parentRoute: typeof chatDotlayoutRoute;
    };
    "/_chat/settings/daemon-key": {
      id: "/_chat/settings/daemon-key";
      path: "/settings/daemon-key";
      fullPath: "/settings/daemon-key";
      preLoaderRoute: typeof settingsSettingsDotdaemonKeyRouteImport;
      parentRoute: typeof chatDotlayoutRoute;
    };
    "/_chat/settings/organization": {
      id: "/_chat/settings/organization";
      path: "/settings/organization";
      fullPath: "/settings/organization";
      preLoaderRoute: typeof settingsSettingsDotorganizationRouteImport;
      parentRoute: typeof chatDotlayoutRoute;
    };
    "/api/auth/$": {
      id: "/api/auth/$";
      path: "/api/auth/$";
      fullPath: "/api/auth/$";
      preLoaderRoute: typeof handlersHandlerDotauthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_chat/bots/$botId/delete": {
      id: "/_chat/bots/$botId/delete";
      path: "/bots/$botId/delete";
      fullPath: "/bots/$botId/delete";
      preLoaderRoute: typeof botsBotsDotbotIdDotdeleteRouteImport;
      parentRoute: typeof chatDotlayoutRoute;
    };
    "/_chat/bots/$botId/edit": {
      id: "/_chat/bots/$botId/edit";
      path: "/bots/$botId/edit";
      fullPath: "/bots/$botId/edit";
      preLoaderRoute: typeof botsBotsDotbotIdDoteditRouteImport;
      parentRoute: typeof chatDotlayoutRoute;
    };
    "/_chat/bots/$botId/wipe-memory": {
      id: "/_chat/bots/$botId/wipe-memory";
      path: "/bots/$botId/wipe-memory";
      fullPath: "/bots/$botId/wipe-memory";
      preLoaderRoute: typeof botsBotsDotbotIdDotwipeMemoryRouteImport;
      parentRoute: typeof chatDotlayoutRoute;
    };
    "/_chat/rooms/$roomId/delete": {
      id: "/_chat/rooms/$roomId/delete";
      path: "/delete";
      fullPath: "/rooms/$roomId/delete";
      preLoaderRoute: typeof roomsRoomsDotroomIdDotdeleteRouteImport;
      parentRoute: typeof roomsRoomsDotroomIdRoute;
    };
    "/_chat/rooms/$roomId/reset": {
      id: "/_chat/rooms/$roomId/reset";
      path: "/reset";
      fullPath: "/rooms/$roomId/reset";
      preLoaderRoute: typeof roomsRoomsDotroomIdDotresetRouteImport;
      parentRoute: typeof roomsRoomsDotroomIdRoute;
    };
    "/_chat/rooms/$roomId/settings": {
      id: "/_chat/rooms/$roomId/settings";
      path: "/settings";
      fullPath: "/rooms/$roomId/settings";
      preLoaderRoute: typeof roomsRoomsDotroomIdDotsettingsRouteImport;
      parentRoute: typeof roomsRoomsDotroomIdRoute;
    };
    "/_chat/rooms/$roomId/wipe-memory": {
      id: "/_chat/rooms/$roomId/wipe-memory";
      path: "/wipe-memory";
      fullPath: "/rooms/$roomId/wipe-memory";
      preLoaderRoute: typeof roomsRoomsDotroomIdDotwipeMemoryRouteImport;
      parentRoute: typeof roomsRoomsDotroomIdRoute;
    };
    "/_chat/rooms/direct/$handle": {
      id: "/_chat/rooms/direct/$handle";
      path: "/rooms/direct/$handle";
      fullPath: "/rooms/direct/$handle";
      preLoaderRoute: typeof roomsRoomsDotdirectDothandleRouteImport;
      parentRoute: typeof chatDotlayoutRoute;
    };
    "/_chat/rooms/direct/$handle/edit": {
      id: "/_chat/rooms/direct/$handle/edit";
      path: "/edit";
      fullPath: "/rooms/direct/$handle/edit";
      preLoaderRoute: typeof roomsRoomsDotdirectDothandleDoteditRouteImport;
      parentRoute: typeof roomsRoomsDotdirectDothandleRoute;
    };
    "/_chat/rooms/direct/$handle/reset": {
      id: "/_chat/rooms/direct/$handle/reset";
      path: "/reset";
      fullPath: "/rooms/direct/$handle/reset";
      preLoaderRoute: typeof roomsRoomsDotdirectDothandleDotresetRouteImport;
      parentRoute: typeof roomsRoomsDotdirectDothandleRoute;
    };
    "/_chat/rooms/direct/$handle/wipe-memory": {
      id: "/_chat/rooms/direct/$handle/wipe-memory";
      path: "/wipe-memory";
      fullPath: "/rooms/direct/$handle/wipe-memory";
      preLoaderRoute: typeof roomsRoomsDotdirectDothandleDotwipeMemoryRouteImport;
      parentRoute: typeof roomsRoomsDotdirectDothandleRoute;
    };
  }
}

interface roomsRoomsDotroomIdRouteChildren {
  roomsRoomsDotroomIdDotdeleteRoute: typeof roomsRoomsDotroomIdDotdeleteRoute;
  roomsRoomsDotroomIdDotresetRoute: typeof roomsRoomsDotroomIdDotresetRoute;
  roomsRoomsDotroomIdDotsettingsRoute: typeof roomsRoomsDotroomIdDotsettingsRoute;
  roomsRoomsDotroomIdDotwipeMemoryRoute: typeof roomsRoomsDotroomIdDotwipeMemoryRoute;
}

const roomsRoomsDotroomIdRouteChildren: roomsRoomsDotroomIdRouteChildren = {
  roomsRoomsDotroomIdDotdeleteRoute: roomsRoomsDotroomIdDotdeleteRoute,
  roomsRoomsDotroomIdDotresetRoute: roomsRoomsDotroomIdDotresetRoute,
  roomsRoomsDotroomIdDotsettingsRoute: roomsRoomsDotroomIdDotsettingsRoute,
  roomsRoomsDotroomIdDotwipeMemoryRoute: roomsRoomsDotroomIdDotwipeMemoryRoute,
};

const roomsRoomsDotroomIdRouteWithChildren =
  roomsRoomsDotroomIdRoute._addFileChildren(roomsRoomsDotroomIdRouteChildren);

interface roomsRoomsDotdirectDothandleRouteChildren {
  roomsRoomsDotdirectDothandleDoteditRoute: typeof roomsRoomsDotdirectDothandleDoteditRoute;
  roomsRoomsDotdirectDothandleDotresetRoute: typeof roomsRoomsDotdirectDothandleDotresetRoute;
  roomsRoomsDotdirectDothandleDotwipeMemoryRoute: typeof roomsRoomsDotdirectDothandleDotwipeMemoryRoute;
}

const roomsRoomsDotdirectDothandleRouteChildren: roomsRoomsDotdirectDothandleRouteChildren =
  {
    roomsRoomsDotdirectDothandleDoteditRoute:
      roomsRoomsDotdirectDothandleDoteditRoute,
    roomsRoomsDotdirectDothandleDotresetRoute:
      roomsRoomsDotdirectDothandleDotresetRoute,
    roomsRoomsDotdirectDothandleDotwipeMemoryRoute:
      roomsRoomsDotdirectDothandleDotwipeMemoryRoute,
  };

const roomsRoomsDotdirectDothandleRouteWithChildren =
  roomsRoomsDotdirectDothandleRoute._addFileChildren(
    roomsRoomsDotdirectDothandleRouteChildren,
  );

interface chatDotlayoutRouteChildren {
  botsBotsDotcreateRoute: typeof botsBotsDotcreateRoute;
  roomsRoomsDotroomIdRoute: typeof roomsRoomsDotroomIdRouteWithChildren;
  roomsRoomsDotcreateRoute: typeof roomsRoomsDotcreateRoute;
  settingsSettingsDotdaemonKeyRoute: typeof settingsSettingsDotdaemonKeyRoute;
  settingsSettingsDotorganizationRoute: typeof settingsSettingsDotorganizationRoute;
  roomsRoomsDotindexRoute: typeof roomsRoomsDotindexRoute;
  botsBotsDotbotIdDotdeleteRoute: typeof botsBotsDotbotIdDotdeleteRoute;
  botsBotsDotbotIdDoteditRoute: typeof botsBotsDotbotIdDoteditRoute;
  botsBotsDotbotIdDotwipeMemoryRoute: typeof botsBotsDotbotIdDotwipeMemoryRoute;
  roomsRoomsDotdirectDothandleRoute: typeof roomsRoomsDotdirectDothandleRouteWithChildren;
}

const chatDotlayoutRouteChildren: chatDotlayoutRouteChildren = {
  botsBotsDotcreateRoute: botsBotsDotcreateRoute,
  roomsRoomsDotroomIdRoute: roomsRoomsDotroomIdRouteWithChildren,
  roomsRoomsDotcreateRoute: roomsRoomsDotcreateRoute,
  settingsSettingsDotdaemonKeyRoute: settingsSettingsDotdaemonKeyRoute,
  settingsSettingsDotorganizationRoute: settingsSettingsDotorganizationRoute,
  roomsRoomsDotindexRoute: roomsRoomsDotindexRoute,
  botsBotsDotbotIdDotdeleteRoute: botsBotsDotbotIdDotdeleteRoute,
  botsBotsDotbotIdDoteditRoute: botsBotsDotbotIdDoteditRoute,
  botsBotsDotbotIdDotwipeMemoryRoute: botsBotsDotbotIdDotwipeMemoryRoute,
  roomsRoomsDotdirectDothandleRoute:
    roomsRoomsDotdirectDothandleRouteWithChildren,
};

const chatDotlayoutRouteWithChildren = chatDotlayoutRoute._addFileChildren(
  chatDotlayoutRouteChildren,
);

interface authAuthDotlayoutRouteChildren {
  authAuthDotforgotPasswordRoute: typeof authAuthDotforgotPasswordRoute;
  authAuthDotresetPasswordRoute: typeof authAuthDotresetPasswordRoute;
  authAuthDotsignInRoute: typeof authAuthDotsignInRoute;
  authAuthDotsignUpRoute: typeof authAuthDotsignUpRoute;
  authAuthDotverifyEmailRoute: typeof authAuthDotverifyEmailRoute;
}

const authAuthDotlayoutRouteChildren: authAuthDotlayoutRouteChildren = {
  authAuthDotforgotPasswordRoute: authAuthDotforgotPasswordRoute,
  authAuthDotresetPasswordRoute: authAuthDotresetPasswordRoute,
  authAuthDotsignInRoute: authAuthDotsignInRoute,
  authAuthDotsignUpRoute: authAuthDotsignUpRoute,
  authAuthDotverifyEmailRoute: authAuthDotverifyEmailRoute,
};

const authAuthDotlayoutRouteWithChildren =
  authAuthDotlayoutRoute._addFileChildren(authAuthDotlayoutRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  indexRoute: indexRoute,
  chatDotlayoutRoute: chatDotlayoutRouteWithChildren,
  authAuthDotlayoutRoute: authAuthDotlayoutRouteWithChildren,
  handlersHandlerDotrobotsRoute: handlersHandlerDotrobotsRoute,
  handlersHandlerDotsitemapRoute: handlersHandlerDotsitemapRoute,
  labLabDotavatarsRoute: labLabDotavatarsRoute,
  authAuthDotsignOutRoute: authAuthDotsignOutRoute,
  handlersHandlerDotrpcRoute: handlersHandlerDotrpcRoute,
  handlersHandlerDotingestRoute: handlersHandlerDotingestRoute,
  handlersHandlerDotauthRoute: handlersHandlerDotauthRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
